#!/usr/bin/env python3
"""Convert a vange-rs OBJ shape to a packed C header for the Pebble face.

Reads vertices (`v x y z` lines, integer coords expected — body-shape.obj from
the convert binary fits in int8_t for every mechos we've checked) and faces
(`f vi//ni ...` lines, 3 or 4 verts per face). Emits:

  - MESH_VERTS[]  : packed int8_t {x, y, z}
  - MESH_EDGES[]  : deduplicated uint8_t {a, b} index pairs
  - count constants

Usage:
  obj_to_header.py <input.obj> <output.h> [--name MESH]
"""
import argparse
import sys
from pathlib import Path


def parse_obj(path: Path):
    verts: list[tuple[int, int, int]] = []
    faces: list[list[int]] = []
    for raw in path.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        tok = line.split()
        if tok[0] == "v":
            x, y, z = (int(round(float(v))) for v in tok[1:4])
            verts.append((x, y, z))
        elif tok[0] == "f":
            idx = [int(t.split("/")[0]) - 1 for t in tok[1:]]
            faces.append(idx)
    return verts, faces


def edges_from_faces(faces: list[list[int]]) -> list[tuple[int, int]]:
    seen: set[tuple[int, int]] = set()
    out: list[tuple[int, int]] = []
    for f in faces:
        for i in range(len(f)):
            a, b = f[i], f[(i + 1) % len(f)]
            key = (a, b) if a < b else (b, a)
            if key not in seen:
                seen.add(key)
                out.append(key)
    return out


def emit(verts, edges, name: str) -> str:
    if len(verts) > 255:
        raise SystemExit(f"too many verts ({len(verts)}) for uint8_t edge indices")
    for x, y, z in verts:
        if not all(-128 <= c <= 127 for c in (x, y, z)):
            raise SystemExit(f"vertex out of int8_t range: {(x, y, z)}")

    lines = [
        "// Auto-generated by tools/obj_to_header.py. Do not edit.",
        "#pragma once",
        "#include <stdint.h>",
        "",
        "typedef struct __attribute__((packed)) { int8_t x, y, z; } MeshVert;",
        "typedef struct __attribute__((packed)) { uint8_t a, b; } MeshEdge;",
        "",
        f"#define {name}_VERT_COUNT {len(verts)}",
        f"#define {name}_EDGE_COUNT {len(edges)}",
        "",
        f"static const MeshVert {name}_VERTS[{name}_VERT_COUNT] = {{",
    ]
    for x, y, z in verts:
        lines.append(f"  {{ {x:>4}, {y:>4}, {z:>4} }},")
    lines.append("};")
    lines.append("")
    lines.append(f"static const MeshEdge {name}_EDGES[{name}_EDGE_COUNT] = {{")
    for a, b in edges:
        lines.append(f"  {{ {a:>3}, {b:>3} }},")
    lines.append("};")
    return "\n".join(lines) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("input", type=Path)
    ap.add_argument("output", type=Path)
    ap.add_argument("--name", default="MESH")
    args = ap.parse_args()

    verts, faces = parse_obj(args.input)
    edges = edges_from_faces(faces)
    args.output.write_text(emit(verts, edges, args.name))
    print(f"wrote {args.output}: {len(verts)} verts, {len(edges)} edges", file=sys.stderr)


if __name__ == "__main__":
    main()
